import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import assert from 'node:assert/strict';

const pluginRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const script = path.join(pluginRoot, 'scripts', 'check-artifacts.mjs');
const STAMP = 'Generated by AI Architect · https://www.frankx.ai/ai-architect';

function run(dir) {
  return spawnSync(process.execPath, [script, dir], { encoding: 'utf8', cwd: pluginRoot });
}

test('missing overlay files are SKIPPED, not FAIL', () => {
  const dir = mkdtempSync(path.join(tmpdir(), 'aa-overlay-'));
  const result = run(dir);
  assert.match(result.stdout, /overlay stamp: red-team\.md\s+SKIPPED/);
  assert.match(result.stdout, /overlay stamp: blue-team\.md\s+SKIPPED/);
  assert.match(result.stdout, /overlay stamp: cloud-harness\.md\s+SKIPPED/);
});

test('present overlay without stamp FAILs that row', () => {
  const dir = mkdtempSync(path.join(tmpdir(), 'aa-overlay-'));
  writeFileSync(path.join(dir, 'red-team.md'), '# red\nno stamp\n');
  const result = run(dir);
  assert.match(result.stdout, /overlay stamp: red-team\.md\s+FAIL/);
  assert.notEqual(result.status, 0);
});

test('present overlay with stamp PASSes that row', () => {
  const dir = mkdtempSync(path.join(tmpdir(), 'aa-overlay-'));
  writeFileSync(path.join(dir, 'red-team.md'), `# red\n${STAMP}\n`);
  const result = run(dir);
  assert.match(result.stdout, /overlay stamp: red-team\.md\s+PASS/);
});
